### ISSUE TITLE
能不能指导下我怎么用Il2cppInspector 

### ISSUE THREAD

**Issue by mosentest** [unreliablecode/Phasmophobia#1]
Il2cppInspector C++ scaffold.
我不会导出这个，求指导

**Comment by unreliablecode** [comment]
the export is not updated

**Comment by mosentest** [comment]
v29 怎么解决

**Comment by unreliablecode** [comment]
> v29 怎么解决

use this fork of il2cppinspector https://github.com/LukeFZ/Il2CppInspectorRedux

**Comment by mosentest** [comment]
有编译好的exe文件吗？我不熟悉编译

**Comment by mosentest** [comment]
Version 2021.1
(c) 2017-2021 Katy Coe - www.djkaty.com - www.github.com/djkaty

Using plugin: IL2CPP API Discovery
Using plugin: Binary metadata field order deobfuscator
Using plugin: Metadata strings XOR decryptor
Using plugin: Binary file XOR decryptor
Extracting metadata from (archive)\assets/bin/Data/Managed/Metadata/global-metadata.dat
The supplied metadata file is not of a supported version (29).
File global-metadata.dat does not exist
Analyze IL2CPP data: 0.15 sec


自己编译的还是这样，我用的plugin来自：
https://github.com/djkaty/Il2CppInspectorPlugins/tags

**Comment by mosentest** [comment]
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Il2CppInspector.CLI.App.Run(Options options) in D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\Program.cs:line 179
   at Il2CppInspector.CLI.App.<>c.<Main>b__7_1(Options options) in D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\Program.cs:line 154
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Il2CppInspector.CLI.App.Main(String[] args) in D:\Downloads\Il2CppInspectorRedux\Il2CppInspector.CLI\Program.cs:line 154


这个问题，要怎么解决呀，老哥
